### ISSUE TITLE
Command cannot be used in this world

### ISSUE THREAD

**Issue by Defeatings** [Qballl/WildernessTp#23]
No console errors, just this when I type /wild.
![screenshot_2](https://user-images.githubusercontent.com/40295362/41465496-0869df5c-70a7-11e8-9802-02c52aa4cff5.png)

**Comment by Qballl** [comment]
You have to add to world the config

**Comment by Defeatings** [comment]
And what exactly do you mean? I've looked around the config file and other files there and nothing mentioned the world.

**Comment by Qballl** [comment]
Look in the config there is a section called worlds you can manually add it there or you can use /wtp gui and then click add worlds/pots/biomes then click world and type in chat your world the minx the maxx the minz and the maxz

**Comment by Defeatings** [comment]
Doing the command in game does nothing, and after I typed the world name corectly in the config and saved, I clicked back to see if anything changed and it disappeared.

**Comment by Defeatings** [comment]
OI! I did something. I played with the /wtp gui a little and now I kinda did something..
everytime I type /wild it teleports me at the spawn, but on top of the building, and gives me this error:
![screenshot_4](https://user-images.githubusercontent.com/40295362/41476374-08da3a86-70ca-11e8-9b07-cb874ab39941.png)

**Comment by Qballl** [comment]
That error literally tells me nothing I need the log for info

**Comment by Defeatings** [comment]
[15:49:26 INFO]: Defeatings issued server command: /wild
[15:49:27 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'wild' in plugin Wild v3.14.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Effect.PORTAL
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_172]
	at org.bukkit.Effect.valueOf(Effect.java:1) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
	at me.Qball.Wild.Utils.TeleportTarget.teleportPlayer(TeleportTarget.java:90) ~[?:?]
	at me.Qball.Wild.Utils.TeleportTarget.teleport(TeleportTarget.java:46) ~[?:?]
	at me.Qball.Wild.Wild.random(Wild.java:316) ~[?:?]
	at me.Qball.Wild.Utils.GetRandomLocation.getRandomLoc(GetRandomLocation.java:57) ~[?:?]
	at me.Qball.Wild.Utils.GetRandomLocation.getWorldInfo(GetRandomLocation.java:40) ~[?:?]
	at me.Qball.Wild.Utils.CheckPerms.check(CheckPerms.java:33) ~[?:?]
	at me.Qball.Wild.Commands.CmdWild.onCommand(CmdWild.java:45) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]

**Comment by Qballl** [comment]
Pastebin your config

**Comment by Defeatings** [comment]
https://pastebin.com/gPjCfaKJ

**Comment by Qballl** [comment]
Alright your factions world is all messed up that may be the problem try to copy the format of world if I weren't on my phone I would do it for you

**Comment by Defeatings** [comment]
Don't really know what do you mean I don't want anything to be deleted.

**Comment by Qballl** [comment]
Here give this a try https://pastebin.com/wYEZHd30

**Comment by Defeatings** [comment]
I pasted that in the config file, restarted, checked to see if the plugin worked, and it did.
After trying /wild literally nothing happened. Nothing in the chat, nothing in the console.

**Comment by Qballl** [comment]
My bad I formatted that wrong I tried using tabs forgetting you can't do that so here is one that checks out https://pastebin.com/kEFBw2iJ

**Comment by Defeatings** [comment]
Thank you for trying, but it won't work sadly..
I checked twice if I pasted the right thing and I did and the same thing as last time, nothing.

**Comment by Qballl** [comment]
Im baffled that should have worked

**Comment by Qballl** [comment]
Any update?

**Comment by Defeatings** [comment]
Gave up on the server, now I'm administrating a much bigger discord server than I had, and soon we will release a better Minecraft server.

**Comment by Qballl** [comment]
Why did you give up on your server

**Comment by Defeatings** [comment]
Because I had to, in order to partnership with the (quite) big server mentioned above

**Comment by Qballl** [comment]
Oh hope it works out but I'm closing this for now
