### ISSUE TITLE
WildTP causes internal server error when any /wild command is used.

### ISSUE THREAD

**Issue by WolfGameStudios** [Qballl/WildernessTp#28]
`[18:07:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'wild' in plugin Wild v3.14.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:675) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1585) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1445) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:37) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:839) [craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:376) [craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792) [craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695) [craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:210) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        at me.Qball.Wild.Commands.CmdWild.onCommand(CmdWild.java:39) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.13.1.jar:git-Bukkit-4228a56]
        ... 15 more`

This error shows up when I try to use the command

**Comment by Qballl** [comment]
Known issue temp fix is disable worldguard hook hopefully will be able to post an update within a week

**Comment by Qballl** [comment]
Posted an update fixing this
