### ISSUE TITLE
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

### ISSUE THREAD

**Issue by olafium** [Qballl/WildernessTp#31]
```
05.01 15:58:44 [Server] ERROR Could not load 'plugins/WildTp.jar' in folder 'plugins'
05.01 15:58:44 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
05.01 15:58:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:163) ~[spigot.1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
05.01 15:58:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
05.01 15:58:44 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:323) [spigot.1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
05.01 15:58:44 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot.1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
05.01 15:58:44 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
05.01 15:58:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
05.01 15:58:44 [Server] INFO Caused by: java.util.zip.ZipException: error in opening zip file
05.01 15:58:44 [Server] INFO at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_171]
05.01 15:58:44 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_171]
05.01 15:58:44 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_171]
05.01 15:58:44 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_171]
05.01 15:58:44 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_171]
05.01 15:58:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:151) ~[spigot.1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
05.01 15:58:44 [Server] INFO ... 5 more
```

Tried it with the latest 3.14.13 build.

**Comment by olafium** [comment]
If I rename the jar to WildTP.jar, it works fine.

**Comment by Qballl** [comment]
Thats what it should be not sure why there is a space

**Comment by olafium** [comment]
I think plugin.yml is case-sensitive. If I download it, it's WildTp.jar, not WildTP.jar.

**Comment by Qballl** [comment]
Closing this as it is now fixed
